import { StandardButton, VerticalBox, ComboBox } from "std-widgets.slint";

// Define a struct to hold window size
export struct Size {
    width: length,
    height: length,
}

export global MapAdapter {
    in-out property <image> map_texture;
    callback render_map();
    callback mouse_press(float, float);
    callback mouse_release(float, float);
    callback mouse_move(float, float, bool);
    callback style_changed(string);
}

export component MapWindow inherits Window {
    // Default window size
    preferred-width: 800px;
    preferred-height: 600px;

    // Expose window size via Size-typed property
    out property<Size> window-size: { width: root.width, height: root.height };

    // Callback when the window size changes
    callback window-size-changed;

    // Invoke callback when window-size changes
    changed window-size => { window-size-changed(); }

    property <[string]> style_urls: [
        "https://demotiles.maplibre.org/style.json",
        "https://tile.openstreetmap.jp/styles/osm-bright/style.json"
    ];

    Timer {
        interval: 200ms;
        running: true;
        triggered => {
            MapAdapter.render_map();
        }
    }

    VerticalBox {
        ComboBox {
            model: root.style_urls;
            selected(url) => {
                MapAdapter.style_changed(url);
            }
        }
        Image {
            source: MapAdapter.map_texture;
            
            touch := TouchArea {
                clicked => {
                    MapAdapter.mouse_press(self.mouse-x / 1px, self.mouse-y / 1px);
                }
            }
        }
    }
}
