import { Button, VerticalBox, ComboBox, HorizontalBox, Slider } from "std-widgets.slint";

// Define a struct to hold window size
export struct Size {
    width: float,
    height: float,
}

// Global adapter for map interaction
export global MapAdapter {
    in-out property <image> map_texture;
    callback tick_map_loop();
    callback mouse_press(x: float, y: float);
    callback mouse_release(x: float, y: float);
    callback mouse_move(x: float, y: float, bool);
    callback wheel_zoom(x: float, y: float, zoom_delta: float);
}

export component MapWidget inherits Rectangle {
    background: green;

    // Expose map image area size so backend can match framebuffer size
    out property<Size> map-size: { width: map.width / 1px, height: map.height / 1px };
    callback map-size-changed(Size);
    changed map-size => {
        debug("Map size changed", map-size);
        map-size-changed(map-size);
    }

    Timer {
        interval: 16ms;
        running: true;
        triggered => {
            MapAdapter.tick_map_loop();
        }
    }

    VerticalBox {
        spacing: 0px;

        map := Image {
            source: MapAdapter.map_texture;
            image-fit: contain;
            vertical-alignment: center;
            horizontal-alignment: center;

            touch := TouchArea {
                property <bool> last-shift: false;
                mouse-cursor: self.pressed ? grabbing : grab;

                pointer-event(e) => {
                    self.last-shift = e.modifiers.shift;

                    if (e.kind == PointerEventKind.down) {
                        MapAdapter.mouse_press(self.mouse-x / 1px, self.mouse-y / 1px);
                    } else if (e.kind == PointerEventKind.up) {
                        MapAdapter.mouse_release(self.mouse-x / 1px, self.mouse-y / 1px);
                    } else if (e.kind == PointerEventKind.move && self.pressed) {
                        MapAdapter.mouse_move(self.mouse-x / 1px, self.mouse-y / 1px, true);
                    }
                }

                scroll-event(event) => {
                    MapAdapter.wheel_zoom(self.mouse-x / 1px,
                                        self.mouse-y / 1px,
                                        event.delta_y / 1px);
                    return accept;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;

    callback get-map-size() -> Size;
    callback map-size-changed <=> map.map-size-changed;
    out property <Size> map-size <=> map.map-size;

    init => {
        debug("MainWindow width: ", self.width, ", Height: ", self.height);
    }

    map:= MapWidget {
        width: root.width;
        height: root.height;
    }
}
